spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BlueWhale?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

aliyun:
  oss:
    endpoint:
    accessKeyId:
    accessKeySecret:
    bucketName:

alipay:
  appId: 9021000149679684
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCKa9v5pB4Zn+98v9crndG6m4yLEqqXVX3maPI0TcBxX1y4aGfLEYSObLKKJbaGJnpo6iylAdNOVo+h7D5LdLc8c6dJAlPHbcW9w5pkhKexPFuIwf0iUyhWMpJaBOX1Su9Xp2nWeLJq0pYAR/vWvMeMWnYx7VcYtfnANvcU/0cNkQKPQ/8IORQ8NkHey70IDl6aLsIUuqaA7dAkcSlkgRXR9gt7FccTgD8uvZ67FV1i7/VdyU/6P+j5AdG25OkQadJd1yFWeuuQROKMM6G4xA2gDO+XVU0vYyZru2VxEuAIOX9dmxgyo+8AAbXd2MUn7ZN9RpsMy6n3XkYnrm9mGha9AgMBAAECggEAM6W9BS+UP5FqZUybN14CdDM3xGhpmF/AwyjjPlrIdETVrsTd/WoC4LV0BJG/wdw3jk/Z6pN8yV0I6KziLXtWJ0sr3tTsd5vgzUZfpCPPAhV4PdXL4nPOuCLUcpwjRVv5Y+ZGWkzcnXkHmQFC2UPE3Pyf308kUUcM8ghQNthtJYUmOijG8PGJWf2Fy1Brx+sQ2dkAuSedNTk9gpiuvHZNTotPIrGFmuTNM4L9kqQGnlsNTBPiNaDL5dh8WvPsIit1q5aHKXciy+QNbpOaPHUnrC7V1TKHfxQQfl3mKx9XbRFg9Tzoa5Kx/wOyTZ1w5C7aaEVxrIRYq8HSO0hc2lbJwQKBgQDvSriOaqdgvNnB9Ryy8gKV9K551iqm4E54abRIpHss9chDVYY6T+J5c+QGXpPsdbiOlvz4vc8KW+FbO86BcIg4XY/n7BFj1vCGjrBkfEnzsXZx9MDzFMsp4J2/gPZxY50xePkdDreWyDf8BjqH/X3K12WrWzjDsi/cUFyupMuD7QKBgQCUFhqXwyM6gENS5cbK7uSx2IS0Y15BmD4T0X7bEFoP9rDGKwTKLohXWezmM+POQ8neBz5t+uIxEmWxT/ZpEXw95M4po4yb+Ihoe9eslaX5zIQmF6ll4rxBfPfOsZr8qXsQkcAlXhPhWu+UKSy/vWdvCr06FlPvw7yVXCJWTw0kEQKBgQCySH2Qvi3OiWXEeJbVTDJY/2AvLj3A70YHuNm1dbbAHK8EW+gR8grOamXtyPF1L5A9zIjV2rUzBpm0m66UCf+z3yGkreGW/UFfP1h0xZVjl0ikRrKraUalANEHKVJz0MABaBxSZfCqyqnLf+iEAX2Db1A0h1aXl17JSqaDCA0JUQKBgHYpEP0JaqGyWIXb7HxelELINlNNepcyaE4d+m/Ho2VbfQASsVa2PHoeueWRf/NEqd2swAa3iiaHvHb4C/EYT59/Y3VcF8UYUZe1QYlnOzGQG93dQYCXo4lJst3NX5K9lQHKmpv2bjyB9+qr1BYGhnLXCdhAmqcU8vPmuUtO9nhRAoGANFCUuDyh8TVIAXh3hc/JDBqmupzn0xOMNq/5c+gYUYU3jG5dF7fxEDSSLpepcjoFyyoPtj7AIk0vTnq2IsxE2cZP94p2ucBoEtAkIA5OIjyPGRyLuOzgFYMe/wy9lwu2ZyvXTXKIGYtnX91IFGEa9r9k/PvZoGAH5HE+bPRYARs=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2K8V3gd4mFIoc+ls45Q8Kf49vZWF1RRf00bK5olr3zqaeZ8dj/Bxb/x/B2CmxFkShCpRguO0reqdNQTcfbVhwfP4ivKR+ORU1T3R4MEi21B1SZwKNSamyEwTPRurKNSmY9gRwaLKDiYnrprlbhEtRcvLaoS0coKiVH/iDyqM74SgNINnPp7jW+p8Dkw4HQcTY+OYqp4rARDVo5QHMQJWn0g1EwGUy6J1AoraZRhYneVUNbA5WY8ZjySYq4pUfcDTkAczQqcaZ9VpgTenMijVyZ+cOSYFvX0WWXr1fJ7dc+raRHxfI3CWrr3FXaoyOPHL+QxKyh7JYFeuy8UM6xpMmwIDAQAB
  notifyUrl: http://v25cee9b.natappfree.cc/api/orders/notify
  serverUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  charset: UTF-8
  signType: RSA2